### PR TITLE
Add basic support of batch requests to `AsyncHTTPProvider`

### LINKED ISSUE #832: Perform batch RPC requests to ethereum node
* Version: 4.2.0
* Python: 3.6
* OS: osx/linux/win

### What was wrong?

There's currently not support for batch requests, when using `HTTPProvider`. Even using IPC/WS connectors I think a speed up could be possible using batch requests.

### How can it be fixed?

Implementing batch requests

### PR DESCRIPTION
**Pull request by dmkulazhenko**
Related to Issue #832 

This PR contains basic/limited support of batch requests for `AsyncHTTPProvider`.

-----

Problem with batch requests is living there for years... and to be honest, there is a lot of things to do to add support of batch requests :cry:.  With this PR I just want to add stuff that is critical for me... and praying that it will motivate someone to finally resolve #832.

#### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by dankvul** [comment]
@fselmo looks like useful stuff at least for beginning, could you review please?

**Comment by lilcryptopump** [comment]
I need this 👀

**Comment by fselmo** [comment]
I've been taking a look here recently and, though this will require some non-trivial refactoring to the code base, it seems like it's not too far off the table for a `v7` implementation. I'll be sure to update here and implement on top of this PR to give credit where it's due. However, merging this in as it stands is not ideal since changes to these methods would cause breaking changes with each iteration.

**Comment by fselmo** [comment]
This was cherry-picked in #3370 and merged. Thanks for getting it going @dmkulazhenko !

**Pull request closed without merging**
