### PR TITLE
Contract Functions utils

### PR DESCRIPTION
**Pull request by reedsa**
### What was wrong?

Related to Issue #3036

### How was it fixed?

Add contract functions methods for `find_by_name`, `find_by_signature` and `find_by_selector`

### Todo:

- [ ] Clean up commit history
- [ ] Add or update documentation related to these changes
- [ ] Add entry to the [release notes](https://github.com/ethereum/web3.py/blob/main/newsfragments/README.md)

#### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by reedsa** [comment]
It is a little awkward to add functions to the API where collisions may occur. These new utilities will exist in the `functions` namespace on a contract, which already contains functions from the contract itself. This is a similar issue we encountered when existing properties could have name collisions with any functions with the same name in the contract.

We could allow these as "reserved" APIs that would not invoke any function on the contract, since the names seem intuitive enough but I'm open to any other thoughts here. I could see us adding `web3` to the name or even finding another namespace to further distinguish this from actual contract functions/events, though I think it's useful to have the ability to filter functions in a similar fashion to what we implemented on the Contract class itself.

**Comment by kclowes** [comment]
> We could allow these as "reserved" APIs that would not invoke any function on the contract, since the names seem intuitive enough but I'm open to any other thoughts here.

Good point. I think this is a good way to do it as long as there is a workaround, just in case someone has a contract method that is called `find_by_name` as unlikely as it may be. But I also think that a different namespace is fine too, whether with the addition of `web3_` on the front, or some other namespace.

**Comment by reedsa** [comment]
@kclowes I'm inclined to leave these and the event APIs out. We talked about the redundancy with the Contract APIs. I would rather not clutter the functions/events with separate capabilities.

Curious if anyone feels strongly about these being available, also would like @fselmo to weigh in here.

**Comment by kclowes** [comment]
Yeah, I honestly think that makes the most sense, but also curious to hear from @fselmo if there is something I'm not thinking of

**Comment by fselmo** [comment]
I'm on board. I think the goal of the original issue was to expose _any_ public utils for getting functions, events, etc. If we did it well enough through the contract instance, I do think that makes sense. We can eventually assess the demand but I think your recent work scratches the itch and is enough to close the original issue @reedsa. Let's work on getting those working well and work on parity across `contract.events` and `contract.functions` and we should be able to close the original issue.

**Pull request closed without merging**
