### PR TITLE
feat(geth): Add debug_traceTransaction RPC method to Geth module

### PR DESCRIPTION
**Pull request by wangereth**
### What was wrong?

Related to Issue #3330 

### How was it fixed?
1. Add debug module in geth.
2. Implement `debug_traceTransaction` RPC Method first

### Todo:

- [ ] Clean up commit history
- [x] Add or update documentation related to these changes
- [x] Add entry to the [release notes](https://github.com/ethereum/<REPO_NAME>/blob/main/newsfragments/README.md)

### CODE REVIEW

**Comment by kclowes** [comment]
Thanks! This looks like the right approach. Let me know when this is ready for review!

**Comment by wangereth** [comment]
> Thanks! This looks like the right approach. Let me know when this is ready for review!

Hello, I implemented `debug_traceTransaction` with `callTracer` config, and tested it myself. Maybe you can help me review it now to check if is it ok.

**Comment by kclowes** [comment]
This looks good so far! Do you mind adding some tests? We'll probably want to add a new file to `web3/_utils/module_testing`, and then the new class will need to be added to the integration tests in `tests/integration/go_ethereum/test_go_ethereum_*.py`. Let me know if you need an example or if you don't have time and/or don't want to and I can take it from here. Thanks!

**Comment by wangereth** [comment]
Sure, I will try to add test, I will ask you for help if there is any questions.

**Comment by wangereth** [comment]
@kclowes I have add some tests, please help review if it's ok.

**Comment by wangereth** [comment]
hi, @kclowes , I have no idea why the py312-core check failed, please have a look.
image
I don't think I have changed code related to the failed test.

**Comment by wangereth** [comment]
` pytest  tests/core/caching-utils/test_generate_cache_key.py --hypothesis-seed=243990134122841475368898544757628869001` will fail, but with any other seed it will success.

**Comment by wangereth** [comment]
image

**Comment by kclowes** [comment]
We're failing on main too, so it's not anything in here. I'm planning to take a look at this PR this week. Thanks for the patience!

**Comment by kclowes** [comment]
Thanks for getting this going @wangereth! I had to rebase to pull in the latest Geth version. I'll add a newsfragment tomorrow and get this in!

**Review by reedsa — APPROVED** [review]
Looks great! 💯 🚢

**Review by pacrob — APPROVED** [review]
:sheep:

**Comment by kclowes** [comment]
Thanks @wangereth!

**Comment by wangereth** [comment]
My pleassure!

**Pull request merged**
