### PR TITLE
Imported missing objects

### PR DESCRIPTION
**Pull request by qraxiss**
### What was wrong?

AsyncGethPersonal, AsyncGethAdmin objects are not imported.
### How was it fixed?

I imported missing objects.

### Todo:
- [x] Add entry to the [release notes](https://github.com/ethereum/web3.py/blob/master/newsfragments/README.md)

### CODE REVIEW

**Comment by kclowes** [comment]
Aw, cute dogs! Thank you for flagging this! We actually shouldn't need to import those any more - all the modules should be loaded by default. Those lines (281-283) can be deleted if you're up for changing this PR?

**Comment by qraxiss** [comment]
web3.py docs
Website still old.

It has been modified in the Github documentation. AsyncEth, AsnyncGet, AsyncGethTxPool and Geth need to be deleted as they are not used(This is what I understand 🙃).

Do I have to throw a new PR for this or can this PR be changed?.

**Comment by kclowes** [comment]
> Do I have to throw a new PR for this or can this PR be changed?

Feel free to update this PR, thank you! We have two versions of the documentation, one for v5 and one for v6 (called `latest`). The master branch corresponds to v6/latest, so you can just make the change in the master branch and it should show up in the `latest` documentation version. If you have the dev dependencies installed, you should be able to run `make docs` from the root of the project at the command line and see a preview of the docs.

**Comment by qraxiss** [comment]
I'm updated.

**Comment by kclowes** [comment]
I'm not sure what happened with the lint here, and I wasn't able to quickly fix it so I cherry-picked your commit and opened another PR at #2820. You should still have credit for the commit on the new PR. Thanks for the contribution!

**Pull request closed without merging**
