### PR TITLE
Replace public addresses with account variables

### PR DESCRIPTION
**Pull request by B3nac**
### What was wrong?

The public addresses used in the documentation were in use by real home grown organic human beings.

Related to Issue #2011

### How was it fixed?

Heroically switched all public addresses with variables. :rocket: 

### Todo:
- [ ] Add entry to the [release notes](https://github.com/ethereum/web3.py/blob/master/newsfragments/README.md)

#### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by fselmo** [comment]
[posted in issue... moving it here]

Hey thanks for getting this moving again 😅 ... I'm still seeing a few addresses that are actual addresses in the docs:

- `0xd3CdA913deB6f67967B99D67aCDFa1712C293601` is still popping up in `web3.geth.rst`, `web3.main.rst`, and `web3.parity.rst`
- `0x5ce9454909639D2D17A3F753ce7d93fa0b9aB12E` is still present in `web3.eth.account.rst` and is a working address on Ropsten and possibly others
- `0x2a65Aca4D5fC5B5C859090a6c34d164135398226` is also on Ropsten possibly others...

I'm not going to keep looking atm but I think there are still quite a few real addresses in the docs. Ideally we can scramble these by replacing one or two letters or numbers.

**Comment by B3nac** [comment]
No problem! Oh snap, I thought it was only `web3.eth.rst` heh heh. Ok I'll review `web3.geth.rst`, `web3.main.rst`, `web3.parity.rst`, and `web3.eth.account.rst as well. :100:

**Comment by B3nac** [comment]
This should work `egrep -rnw '0x[a-fA-F0-9]{40}' ~/web3.py/docs` just need to replace every instance now.

**Comment by B3nac** [comment]
@fselmo I think I got em all. Let me know what you think, cheers!

**Comment by reedsa** [comment]
@B3nac there are merge conflicts/test failures from this being a bit stale. Any chance of coming back to this or should we proceed to take it on?

**Comment by B3nac** [comment]
Hey @reedsa! Yeah lemme give it the ole college try to resync my branch with justice and glory.

**Comment by B3nac** [comment]
I have to go back through each doc page individually because there has been style changes to snake_case for some functions, so this is going to take me awhile.

**Comment by B3nac** [comment]
@reedsa ok everything should be good now, for the love of bob please merge :rofl:. 

Seriously though let me know if I missed anything. Cheers!

**Comment by reedsa** [comment]
Thanks for taking that on and for the quick update! Appreciate the time you've sunk into this.
One improvement we'd like to make is to adjust these so they render as placeholder variables rather than strings to make it more distinguished.
I noticed the tests for docs are also failing. Before we merge I plan to fix those in addition to updating the address strings to appear more like variables. Will push a commit soon!

**Pull request merged**
